name: Build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        continue-on-error:
        - false
        java:
        - 8
        - 11
        - 16
        os:
        - ubuntu
        - windows
    continue-on-error: ${{ matrix.continue-on-error }}
    env:
      MAIN_JAVA: 11
      MAIN_OS: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
        architecture: x64
    - uses: actions/cache@preview
      id: cache-gradle
      with:
        path: ~/.gradle/caches
        key: gradle

    - run: ./gradlew build --stacktrace
      if: runner.os != 'Windows'
    - run: .\gradlew build --stacktrace
      if: runner.os == 'Windows'

    - run: ./gradlew jacocoTestReport coveralls
      if: matrix.os == env.MAIN_OS && matrix.java == env.MAIN_JAVA
      continue-on-error: true
    - uses: codecov/codecov-action@v1
      if: matrix.os == env.MAIN_OS && matrix.java == env.MAIN_JAVA
      continue-on-error: true
